name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
# 1. Download artifact
# 2. Deploy to github pages

# Useful actions
#  dawidd6/action-download-artifact@v2
#  crazy-max/ghaction-github-pages@v3
